version: "3"

services:
  rest:
    image: node:latest 
    volumes:
      - ./:/challenge
    working_dir: /challenge
    environment:
      NODE_ENV: development  
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    command: npm run dev
    
  mongo:
    image: mongo
    volumes:
     - mongo_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo_data:

     
       